---
groups:
- name: misthos-web
  jobs: [test,build-and-push-to-staging]
- name: pipeline-image
  jobs: [build-task-image]

jobs:
- name: test
  plan:
  - {get: repo, trigger: true}
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      caches:
      - path: deps
      inputs:
      - name: repo
      run:
        path: repo/ci/tasks/run-tests.sh
- name: build-and-push-to-staging
  plan:
  - {get: repo, trigger: true, passed: [test]}
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      caches:
      - path: deps
      inputs:
      - name: repo
      outputs:
      - name: build
      run:
        path: repo/ci/tasks/build.sh
  - task: deploy-staging
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      inputs:
      - name: repo
      - name: build
      params:
          GCP_SERVICE_ACCOUNT: ((gcp-service-account))
      run:
        path: repo/ci/tasks/deploy-staging.sh
- name: build-task-image
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: pipeline-ci-image/ci/ci_image

resources:
- name: repo
  type: git
  source:
    ignore_paths: [infra/*, ci/*]
    uri: git@github.com:misthosio/misthos.git
    branch: master
    private_key: ((github-ssh-key.private_key))
- name: pipeline-ci-image
  type: git
  source:
    uri: git@github.com:misthosio/misthos.git
    branch: master
    paths: [ci/ci_image/*]
    private_key: ((github-ssh-key.private_key))
- name: docker-image-ci
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: misthosio/misthos-web-pipeline
