---
groups:
- name: misthos-web
  jobs: [test, bump-minor,bump-patch, build, deploy-staging, deploy-testnet]
- name: pipeline-image
  jobs: [build-task-image]

jobs:
- name: bump-minor
  public: true
  plan:
    - { get: misthos-build, trigger: true,  passed: [deploy-testnet] }
    - { get: version, params: {bump: minor}, passed: [deploy-testnet] }
    - { put: version,                 params: {file: version/number} }

- name: bump-patch
  public: true
  plan:
    - { get: misthos-build, trigger: true, passed: [build] }
    - { get: version, params: {bump: patch}, passed: [build] }
    - { put: version,                params: {file: version/number} }

- name: test
  plan:
  - aggregate:
    - {get: repo, trigger: true}
    - {get: pipeline-tasks}
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      caches:
      - path: deps
      inputs:
      - name: pipeline-tasks
      - name: repo
      run:
        path: pipeline-tasks/ci/tasks/run-tests.sh
- name: build
  plan:
  - aggregate:
    - {get: repo, trigger: true, passed: [test]}
    - {get: version, trigger: false, params: {bump: patch}}
    - {get: pipeline-tasks}
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      caches:
      - path: deps
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: version
      outputs:
      - name: build
      run:
        path: pipeline-tasks/ci/tasks/build.sh
  - put: misthos-build
    params:
      file: build/misthos-build-*.tgz

- name: deploy-staging
  plan:
  - aggregate:
    - {get: misthos-build, trigger: true, passed: [build]}
    - {get: repo, trigger: false, passed: [build]}
    - {get: version, trigger: false, passed: [build]}
    - {get: pipeline-tasks}
  - task: deploy-staging
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      inputs:
      - name: pipeline-tasks
      - name: misthos-build
      params:
          GCP_SERVICE_ACCOUNT: ((gcp-service-account))
          DEPLOY_ENVIRONMENT: staging
      run:
        path: pipeline-tasks/ci/tasks/deploy.sh
  - put: staging-branch
    params: {repository: repo, tag: version/version, tag_prefix: "v", force: true}

- name: deploy-testnet
  plan:
  - aggregate:
    - {get: misthos-build, trigger: false, passed: [deploy-staging]}
    - {get: version, trigger: false, passed: [deploy-staging]}
    - {get: repo, trigger: false, passed: [deploy-staging]}
    - {get: pipeline-tasks}
  - task: deploy-testnet
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-web-pipeline}
      inputs:
      - name: pipeline-tasks
      - name: misthos-build
      params:
          GCP_SERVICE_ACCOUNT: ((gcp-service-account))
          DEPLOY_ENVIRONMENT: testnet
      run:
        path: pipeline-tasks/ci/tasks/deploy.sh
  - put: testnet-branch
    params: {repository: repo, tag: version/version, tag_prefix: "v", force: true}

- name: build-task-image
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: pipeline-ci-image/ci/ci_image

resources:
- name: repo
  type: git
  source:
    ignore_paths: [infra/*, ci/*, Makefile]
    uri: git@github.com:misthosio/misthos.git
    branch: master
    private_key: ((github-ssh-key.private_key))
- name: staging-branch
  type: git
  source:
    uri: git@github.com:misthosio/misthos.git
    branch: staging
    private_key: ((github-ssh-key.private_key))
- name: testnet-branch
  type: git
  source:
    uri: git@github.com:misthosio/misthos.git
    branch: testnet
    private_key: ((github-ssh-key.private_key))
- name: misthos-build
  type: gcs-resource
  source:
    bucket: artifact-cache
    json_key: ((gcp-service-account))
    regexp: misthos-build-v(.*).tgz
- name: version
  type: semver
  source:
    driver: gcs
    bucket: artifact-cache
    key: misthos-build-version
    json_key: ((gcp-service-account))
- name: pipeline-ci-image
  type: git
  source:
    uri: git@github.com:misthosio/misthos.git
    branch: master
    paths: [ci/ci_image/*]
    private_key: ((github-ssh-key.private_key))
- name: pipeline-tasks
  type: git
  source:
    uri: git@github.com:misthosio/misthos.git
    branch: master
    paths: [ci/tasks/*, Makefile]
    private_key: ((github-ssh-key.private_key))
- name: docker-image-ci
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: misthosio/misthos-web-pipeline

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
